server:
  port: 8090

spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/movie_store
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: movie-store-services

project:
  poster: posters/

base:
  url: "http://localhost:8090"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8989/eureka






